# ----------------------- #
#          Jekyll         #
# ----------------------- #
# All of these settings are required


title: "Crediton Cemetery Heritage Portal"
description: "A platform for exploring and preserving the history of Crediton Cemetery."

# Set this to true to disable plugins
# safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
# regeneration:       true
# Changes the port that the Jekyll server will run on
# port:               4000
# Sets site.url, useful for environment switching
url:                https://marketingpip.github.io/
# Changes the directory where Jekyll will look to transform files
# source:             ./
# Changes the directory where Jekyll will write files to
# destination:        _site
# Changes the directory where Jekyll will look for plugins
plugins_dir:        _plugins
baseurl: "/"

# Optional: You can define where your posts are located (if in a custom folder)
#posts_dir: "pages/blog"
posts_dir: "_posts"

# Inclusion of recent posts in sidebar
# recent_posts:       false
# Inclusion/exclusion of future dated posts
future:             false
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                false
# Uses [engine] instead of Maruku
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
  syntax_highlighter_opts:
    disable : true
highlighter: none
# Controls the URLs that posts are generated with.
permalink: /blog/:title/
# permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:
  - pages
  - pages/blog
  - pages/blog/author
  - pages/exibits
  - pages/exibits/history_of_town
  - bin
  - action-build
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.md
  - requirements.txt
  - package.json
  - vendor
# Timezone for timestamp conversion
timezone: UTC

# RSS Feeds
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

collections:
  authors:
    output: true
    permalink: /blog/authors/:path/
  blog:
    output: true
    permalink: /blog/:title/


# Plugins
plugins:
  - jekyll-sitemap
  - file_creation_date
  - expire_posts

# _config.yml
minify:
  css: true    # Enable CSS minification
  js: true     # Enable JS minification  
