title: ''
description: A platform for exploring and preserving the history of Crediton Cemetery.
url: https://marketingpip.github.io
plugins_dir: _plugins
baseurl: /
logo: assets/images/Crediton_Heritage_Logo3.svg
posts_dir: _posts
future: false
lsi: false
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
  syntax_highlighter_opts:
    disable: true
highlighter: none
permalink: /blog/:title/
exclude:
  - pages
  - pages/blog
  - pages/blog/author
  - pages/exibits
  - pages/exibits/history_of_town
  - bin
  - action-build
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.md
  - requirements.txt
  - package.json
  - vendor
  - _webpack
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
timezone: UTC
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
paginate: 6
paginate_path: /blog/page:num/
collections:
  authors:
    output: true
    permalink: /authors/:path/
  books:
    output: true
    permalink: /resources/:collection/:slug/
  exhibits:
    output: true
    permalink: /exhibits/:slug/
defaults:
  - scope:
      path: assets/people
    values:
      people: true
  - scope:
      path: resources/**/*.pdf
    values:
      sitemap: false
plugins:
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-purge-css
  - jekyll-minifier
  - jekyll-terser
  - jekyll-archives-v2
jekyll-minifier:
  compress_javascript: false
  compress_css: false
  exclude:
    - robots.txt
    - search.json
    - assets/js/pwa/manifest.json
PurgeCSS:
  content:
    - _site/**/*.html
    - _site/**/*.js
  css:
    - _site/assets/css/font-awesome.css
  output: _site/assets/css/
jekyll-archives:
  posts:
    enabled:
      - year
      - tags
      - categories
    layout: tag
    permalinks:
      year: /blog/:year/
terser:
  compress:
    drop_console: true
assets:
  compress: true
  minify: true
gh_repo_name: cemetery_demo-
download_images_folder: assets/images
og_template: _includes/og-template.html
include:
  - assets
exhibits_index_template: _layouts/exhibits_index.html
blog_index_template: _layouts/tag.html
resources:
  - name: Resources
    url: resources
  - name: Frequently Asked Questions
    url: faq
  - name: Contact Us
    url: contact-us
  - name: Support Us
    url: support-us
  - name: Blog
    url: blog
  - name: Cemetery Fees
    url: cemetery-fees
  - name: Statistics
    url: statistics
policys:
  - name: Privacy Policy
    url: privacy-policy
  - name: Terms of Service
    url: terms-of-service
json_api:
  posts: true
  authors: true
  categories: true
  tags: true
social:
  - name: Github
    url: https://github.com/themesberg/flowbite
    icon: fab fa-github
  - name: Discord
    url: https://discord.gg/4eeurUVvTy
    icon: fab fa-discord
  - name: Twitter
    url: https://twitter.com/
    icon: fab fa-twitter
