# ----------------------- #
#          Jekyll         #
# ----------------------- #
# All of these settings are required


title: "Crediton Cemetery Heritage Portal"
description: "A platform for exploring and preserving the history of Crediton Cemetery."

# Set this to true to disable plugins
# safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
# regeneration:       true
# Changes the port that the Jekyll server will run on
# port:               4000
# Sets site.url, useful for environment switching
url:                https://marketingpip.github.io
# Changes the directory where Jekyll will look to transform files
# source:             ./
# Changes the directory where Jekyll will write files to
# destination:        _site
# Changes the directory where Jekyll will look for plugins
plugins_dir:        _plugins
baseurl: "/"

logo: "assets/images/Crediton_Heritage_Logo3.svg" # Replace with your logo URL
## env: production

# Optional: You can define where your posts are located (if in a custom folder)
#posts_dir: "pages/blog"
posts_dir: "_posts"

# Inclusion of recent posts in sidebar
# recent_posts:       false
# Inclusion/exclusion of future dated posts
future:             false
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                false
# Uses [engine] instead of Maruku
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
  syntax_highlighter_opts:
    disable : true
highlighter: none
# Controls the URLs that posts are generated with.
permalink: /blog/:title/
# permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:
  - pages
  - pages/blog
  - pages/blog/author
  - pages/exibits
  - pages/exibits/history_of_town
  - bin
  - action-build
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.md
  - requirements.txt
  - package.json
  - vendor
# Timezone for timestamp conversion
timezone: UTC

# RSS Feeds
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

paginate: 2 # Number of items per page (adjust as needed)
paginate_path: "/blog/page:num/" # Path for pagination (for example, /page2/, /page3/, etc.)

collections:
  authors:
    output: true
    permalink: /blog/authors/:path/
#  blog:
#    output: true
#   permalink: /blog/:slug/
  books:
    output: true
    permalink: /resources/:collection/:title/
  exhibits:
    output: true
    permalink: /exhibits/:slug/    
    pagination:
      enabled: true
      per_page: 5
      paginate_path: "/exhibits/page:num/"
      index_file: "index.html"
      layout: "exhibits_index"    
# Plugins
plugins:
 # - octopress-minify-html
  - jekyll-sitemap
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-paginate
 
assets:
  compress: true  # Enable CSS and JS compression
  minify: true    # Enable HTML minification

gh_repo_name: cemetery_demo- # required for downloading images

download_images_folder: "assets/images"

og_template: _includes/og-template.html

# Ensure assets/images is copied into the build directory
include:
  - assets

# Page Tags

tag_page_layout: tag_page
tag_page_dir: blog/tag



# Footer
resources:
  - name: "Resources"
    url: "resources"
  - name: "Frequently Asked Questions"
    url: "faq"
  - name: "Contact Us"
    url: "contact-us"
  - name: "Support Us"
    url: "support-us"      
  - name: "Blog"
    url: "blog"   

policys:
  - name: "Privacy Policy"
    url: "privacy-policy"
  - name: "Terms of Service"
    url: "terms-of-service"
    
social:
  - name: "Github"
    url: "https://github.com/themesberg/flowbite"
    icon: "M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z"
  - name: "Discord"
    url: "https://discord.gg/4eeurUVvTy"
    icon: "M16.942 1.556a16.3 16.3 0 0 0-4.126-1.3 12.04 12.04 0 0 0-.529 1.1 15.175 15.175 0 0 0-4.573 0 11.585 11.585 0 0 0-.535-1.1 16.274 16.274 0 0 0-4.129 1.3A17.392 17.392 0 0 0 .182 13.218a15.785 15.785 0 0 0 4.963 2.521c.41-.564.773-1.16 1.084-1.785a10.63 10.63 0 0 1-1.706-.83c.143-.106.283-.217.418-.33a11.664 11.664 0 0 0 10.118 0c.137.113.277.224.418.33-.544.328-1.116.606-1.71.832a12.52 12.52 0 0 0 1.084 1.785 16.46 16.46 0 0 0 5.064-2.595 17.286 17.286 0 0 0-2.973-11.59ZM6.678 10.813a1.941 1.941 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.919 1.919 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Zm6.644 0a1.94 1.94 0 0 1-1.8-2.045 1.93 1.93 0 0 1 1.8-2.047 1.918 1.918 0 0 1 1.8 2.047 1.93 1.93 0 0 1-1.8 2.045Z"
  - name: "Twitter"
    url: "https://twitter.com/"
    icon: "M20 1.892a8.178 8.178 0 0 1-2.355.635 4.074 4.074 0 0 0 1.8-2.235 8.344 8.344 0 0 1-2.605.98A4.13 4.13 0 0 0 13.85 0a4.068 4.068 0 0 0-4.1 4.038 4 4 0 0 0 .105.919A11.705 11.705 0 0 1 1.4.734a4.006 4.006 0 0 0 1.268 5.392 4.165 4.165 0 0 1-1.859-.5v.05A4.057 4.057 0 0 0 4.1 9.635a4.19 4.19 0 0 1-1.856.07 4.108 4.108 0 0 0 3.831 2.807A8.36 8.36 0 0 1 0 14.184 11.732 11.732 0 0 0 6.291 16 11.502 11.502 0 0 0 17.964 4.5c0-.177 0-.35-.012-.523A8.143 8.143 0 0 0 20 1.892Z"
