# ----------------------- #
#          Jekyll         #
# ----------------------- #
# All of these settings are required


title: "Crediton Cemetery Heritage Portal"
description: "A platform for exploring and preserving the history of Crediton Cemetery."

# Set this to true to disable plugins
# safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
# regeneration:       true
# Changes the port that the Jekyll server will run on
# port:               4000
# Sets site.url, useful for environment switching
url:                https://marketingpip.github.io/
# Changes the directory where Jekyll will look to transform files
# source:             ./
# Changes the directory where Jekyll will write files to
# destination:        _site
# Changes the directory where Jekyll will look for plugins
plugins_dir:        _plugins
baseurl: "/"

env: production

# Optional: You can define where your posts are located (if in a custom folder)
#posts_dir: "pages/blog"
posts_dir: "_posts"

# Inclusion of recent posts in sidebar
# recent_posts:       false
# Inclusion/exclusion of future dated posts
future:             false
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                false
# Uses [engine] instead of Maruku
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
  syntax_highlighter_opts:
    disable : true
highlighter: none
# Controls the URLs that posts are generated with.
permalink: /blog/:title/
# permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:
  - pages
  - pages/blog
  - pages/blog/author
  - pages/exibits
  - pages/exibits/history_of_town
  - bin
  - action-build
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.md
  - requirements.txt
  - package.json
  - vendor
# Timezone for timestamp conversion
timezone: UTC

# RSS Feeds
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

collections:
  authors:
    output: true
    permalink: /blog/authors/:path/
  blog:
    output: true
    permalink: /blog/:title/


# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-assets

jekyll-minifier:
  preserve_php: true                # Default: false
  remove_spaces_inside_tags: true   # Default: true
  remove_multi_spaces: true         # Default: true
  remove_comments: true             # Default: true
  remove_intertag_spaces: true      # Default: false
  remove_quotes: false              # Default: false
  compress_css: true                # Default: true
  compress_javascript: true         # Default: true
  compress_json: true               # Default: true
  simple_doctype: false             # Default: false
  remove_script_attributes: false   # Default: false
  remove_style_attributes: false    # Default: false
  remove_link_attributes: false     # Default: false
  remove_form_attributes: false     # Default: false
  remove_input_attributes: false    # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false       # Default: false
  remove_https_protocol: false      # Default: false
  preserve_line_breaks: false       # Default: false
  simple_boolean_attributes: false  # Default: false
  compress_js_templates: false      # Default: false
  preserve_patterns:                # Default: (empty)
  uglifier_args:                    # Default: (empty)
minify_html: true

assets:
  compress: true  # Enable CSS and JS compression
  minify: true    # Enable HTML minification
