# ----------------------- #
#          Jekyll         #
# ----------------------- #
# All of these settings are required

# Set this to true to disable plugins
# safe:               false
# Enables or disables Jekyll from recreating the site when files are modified.
# regeneration:       true
# Changes the port that the Jekyll server will run on
# port:               4000
# Sets site.url, useful for environment switching
# url:                http://josediazgonzalez.com
# Changes the directory where Jekyll will look to transform files
# source:             ./
# Changes the directory where Jekyll will write files to
# destination:        _site
# Changes the directory where Jekyll will look for plugins
# plugins_dir:        _plugins

# Inclusion of recent posts in sidebar
# recent_posts:       false
# Inclusion/exclusion of future dated posts
# future:             true
# Produces an index for related posts. Install rb-gsl and libgsl to speed this up
lsi:                false
# Uses [engine] instead of Maruku
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: false
  syntax_highlighter_opts:
    disable : true
highlighter: none
# Controls the URLs that posts are generated with.
permalink:          /:year/:month/:day/:title/
# A list of directories and files to exclude from the conversion
exclude:
  - bin
  - action-build
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Rakefile
  - README.md
  - requirements.txt
  - package.json
  - vendor
# Timezone for timestamp conversion
timezone: UTC
