name: Convert CSV to JSON

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch
  workflow_dispatch:  # Allow manual trigger

jobs:
  convert_csv_to_json:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code in the repository

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Set the Node.js version to use (adjust based on your project)

    - name: Install dependencies
      run: |
        npm install  # Install npm dependencies (ensure 'papaparse' and others are listed in package.json)

    - name: Run CSV to JSON conversion script
      run: |
        node .github/workflows/csv-to-json.js  # Path to your script in .github/workflows/

    - name: Upload resulting JSON as artifact
      uses: actions/upload-artifact@v2
      with:
        name: output-json
        path: output.json  # Specify the path to your output JSON file

    - name: Commit and push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add output.json
        git commit -m "Add converted CSV to JSON output"
        git push
