# This workflow builds and deploys a Jekyll site to GitHub Pages.
name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips
          
          # Install wkhtmltopdf from the PPA repository
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:alessandro-strada/ppa -y
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5



      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production


      # Install Node as this is needed for PurgeCSS
      - name: Setup Node
        run: |
          npm install -g purgecss
          purgecss -c purgecss.config.js

      - name: Compress Images in _site/assets
        uses: MarketingPipeline/Image-Optimizer-Action@main
        with:
          filename: assets/
          recursion: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
