name: Echo Input Workflow

# This is the trigger to allow manual dispatching of the workflow via API
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'Home location'
        required: true
        default: 'San Francisco, CA'

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo input values
        run: |
          echo "Name: ${{ github.event.inputs.name }}"
          echo "Home: ${{ github.event.inputs.home }}"
